version: 2.1


orbs:
  maven: circleci/maven@0.0.12
  python: circleci/python@0.3.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - persist_to_workspace:
          root: /root
          paths:
             - project
      - run:
          name: Build project
          command: mvn clean verify -DskipTests
  python_build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - attach_workspace:
          at: /root
      - run:
          command: |
            python3 samplePythonScript.py
          name: Run word count script

workflows:
  maven_build:
    jobs:
      - build
      - python_build:
          requires:
            - build
      - maven/test:
          requires:
            - python_build