version: 2.1


orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Build project
          command: mvn clean verify -DskipTests

workflows:
  maven_build:
    jobs:
      - build
      - maven/test # checkout, build, test, and upload test results

